### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by timgrossner** [daveriesz/rigsync#2]
list.c: In function ‘set_rig_port’:
list.c:47:54: error: ‘FILPATHLEN’ undeclared (first use in this function)
   47 |   strncpy(rig->rig->state.rigport.pathname, portstr, FILPATHLEN - 1);
      |                                                      ^~~~~~~~~~
list.c:47:54: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:42: list.o] Error 1

**Comment by daveriesz** [comment]
Hi, Tim.  FILPATHLEN is defined in /usr/include/hamlib/rig.h.  I'm building against Hamlib 3.3.  What version do you have installed?

As a workaround, you might try adding a define to the CDEF macro in the Makefile:

   CDEF = -DFILEPATHLEN=512

**Comment by timgrossner** [comment]
That didn't do the trick, but check this out: https://github.com/kubernetes/klog/issues/243
My hamlib version is 4.5

**Comment by daveriesz** [comment]
I updated the code to use the new macro if it is defined.
