### ISSUE TITLE
Sorry, this is no hurry...issue with changing SDR freq

### ISSUE THREAD

**Issue by timgrossner** [daveriesz/rigsync#4]
I have this working now, thanks for that patch tonight.

I am using an FTDX10 and SDR++, with it's built-in rigctl server.
One thing though, the physical rig seems to be the only one of the two that it will allow to change the frequency. It changes frequency when i click/tune/etc on the SDR++ side, but immediately jumps back to the frequency on the FTDX10. I've tried switching the startup rig places, "/usr/local/bin/rigsync -m 2 -r localhost:4533 -m 2 -r localhost:4532 -n 2" vs "/usr/local/bin/rigsync -m 2 -r localhost:4532 -m 2 -r localhost:4533 -n 2", I've tried it without the -n flag, etc. 

Any thoughts?

**Comment by daveriesz** [comment]
Can you describe your setup?  Are you connecting to the Yaesu through rigctld?  I haven't tested that configuration but I can try it out.  If this is what you're doing, what command are you using to set up the rigctld server for the Yaesu?

The issue may be that the server for the Yaesu isn't changing the frequency of the radio and, when the radio's frequency is subsequently read again, the original frequency is interpreted as a new frequency change.  Then, the SDR's frequency is adjusted to match.  This would be a bug in rigsync.

Can you use rigctl to change the frequency of the Yaesu directly?

**Comment by timgrossner** [comment]
Sure, I have an FTDX10 connected via usb, which I had to get the latest version of rigctld for, as well as that pretty new version of hamlib. I run it with the following: rigctld -m 1042 -r /dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_00B5DD4B-if00-port0 -t 4533

I am using SDR++ as the SDR, using it's rigctl daemon: /usr/local/bin/rigsync -m 2 -r localhost:4533 -m 2 -r localhost:4532 -n 2

With your rigsync, I attempted to keep the original FTDX10 rigctld running and just have it talk to both TCP ports. It actually works pretty well, other than the fact that I can't tune with the SDR++ app. When I try to run rigsync with a "-m 1042", it segfaults. I think that might be because of the manually installed updated version of rigctld.

**Comment by daveriesz** [comment]
After you've started rigctld, try using rigctl to attach to it and change
the frequency.  Something like:

    rigctl -m 2 -rlocalhost:4533 F 10000000

**Comment by timgrossner** [comment]
I just tried it, but that didn't work. However, I did figure out a small workaround - if I uncheck the "Tuning" button in SDR++, which disables tuning input I believe, it still syncs from SDR++ -> the hardware rig. But, obviously, not the other way around.

**Comment by daveriesz** [comment]
Okay, I can reproduce this.  I attached to my TS-870S and FT-857D and both show the same issue with not only SDR++ but also each other.  It shows up whether everything is running over a server or serial port.

I think that if the frequency changes more than once per sync operation the rigsync logic gets confused.  If you turn the dial by, say, one increment per second the rigs will keep up with each other.  I need to go back into the logic and work this out.

It seems to be something I should have noticed long ago. I don't know why I'm only seeing it now that you've pointed it out to me.

**Comment by timgrossner** [comment]
Hey, no sweat man! Your rig sync system at least doesn't cause SDR++'s
rigctl to crash, like every other example I've tried out there. And like I
said if I uncheck the tune box on SDR++, it does what I would like anyway.

I'll keep watch for updates! Let me know if I can help test.

**Comment by daveriesz** [comment]
I appreciate the feedback Tim.  Stay subscribed to this issue and you'll be notified when I have a fix.

**Comment by daveriesz** [comment]
I've checked in a fix to the "issue4" branch.  It works for me using SDR++ and two physical rigs (in both serial and server modes) simultaneously.  Please give it a test when you get a chance.

**Comment by timgrossner** [comment]
I grabbed a copy, recompiled and replaced the binary in my /usr/local/bin dir, and am still seeing it only work when tuning from the transceiver. If I tune from the SDR++, it jumps right back to the frequency of the Yaesu.

My script to start up stuff:
#!/bin/bash


echo "Starting RIGCTLD..."
rigctld -m 1042 -r /dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_00B5DD4B-if00-port0 -t 4533 &

sleep 3
/usr/local/bin/rigsync -m 2 -r localhost:4533 -m 2 -r localhost:4532 -n 2 &

**Comment by daveriesz** [comment]
Can you run it with the "-d 2" argument?

**Comment by timgrossner** [comment]
I tried switching the order of which server:port to 
-m 2 -r localhost:4532 -m 2 -r localhost:4533 -n 2
and it's working more ask expected, with the rig following the SDR. 

Sure, will try that next.

**Comment by timgrossner** [comment]
tgrossner@hamshack:~$ ftdx10-rigctl-interface/ftdx10startradiosync 
Starting RIGCTLD...
DEBUG: debug level set: 2
DEBUG: rig count = 2
DEBUG: opened rig: model 2, port localhost:4532, speed 0
DEBUG: opened rig: model 2, port localhost:4533, speed 0
DEBUG: rig 0: reading initial state
DEBUG: rig 0 is dirty: old=           0.00Hz/    new=  14,210,000.00Hz/USB
DEBUG:         clearing dirty flag
DEBUG: rig 1: reading initial state
DEBUG: rig 1 is dirty: old=           0.00Hz/    new=  14,210,000.00Hz/USB
DEBUG:         clearing dirty flag
DEBUG: reading states again
DEBUG: dirty rig: 1
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 1
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,210,000.00Hz/USB
DEBUG: rig_write_state() req=  14,210,000.00Hz/USB act=  14,210,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,210,000.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,210,000.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: rig_write_state() req=  14,232,000.00Hz/USB act=  14,232,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,232,000.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,232,000.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,232,000.00Hz/USB new=  14,229,490.00Hz/USB
DEBUG: rig_write_state() req=  14,232,000.00Hz/USB act=  14,229,490.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,232,000.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,229,490.00Hz/USB new=  14,228,890.00Hz/USB
DEBUG: rig_write_state() req=  14,232,000.00Hz/USB act=  14,228,890.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,232,000.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,228,890.00Hz/USB new=  14,228,890.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,228,890.00Hz/USB new=  14,229,950.00Hz/USB
DEBUG: rig_write_state() req=  14,232,000.00Hz/USB act=  14,229,950.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,232,000.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,229,950.00Hz/USB new=  14,227,700.00Hz/USB
DEBUG: rig_write_state() req=  14,232,000.00Hz/USB act=  14,227,700.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,232,000.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,227,700.00Hz/USB new=  14,227,700.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,227,700.00Hz/USB new=  14,232,000.00Hz/USB
DEBUG: rig_write_state() req=  14,232,000.00Hz/USB act=  14,232,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,232,000.00Hz/USB new=  14,233,000.00Hz/USB
DEBUG: dirty rig: 0
DEBUG: rig 1 is dirty: old=  14,232,000.00Hz/USB new=  14,233,000.00Hz/USB
DEBUG: rig_write_state() req=  14,233,000.00Hz/USB act=  14,233,000.00Hz/USB
DEBUG: rig 0 is dirty: old=  14,233,000.00Hz/USB new=  14,233,000.00Hz/USB
DEBUG: rig 1 is dirty: old=  14,233,000.00Hz/USB new=  14,233,000.00Hz/USB
DEBUG: dirty rig: 0
^C

**Comment by daveriesz** [comment]
Phooey.  I can't repro this one.  It might be something with the FTDX10 that hamlib isn't handling as expected.  Or SDR++'s server implementation is different.  Or (more likely) my own bugs.  I'll need more time to brainstorm this.

What software versions are you using (OS, hamlib, SDR++)?

**Comment by daveriesz** [comment]
I tried moving from hamlib 3.3 to hamlib 4.4.  Now I can't get the Yaesu (FT857D) to follow SDR++ no matter which order the rigs are defined.  I don't know whether this is a manifestation of the issue you're experiencing, but I'll try to fix this one and see if it helps your setup.

**Comment by timgrossner** [comment]
Sounds to me like the common failure here is hamlib 4.x, no?

**Comment by daveriesz** [comment]
There's always the possibility that my code was never initializing or managing the rigs correctly.  The documentation is quite lacking, so it's difficult to tell.  For certain, 4.4 does not work the same as 3.3.

I'm still working on it, though.  Hopefully I can figure out where it's all going haywire.

**Comment by daveriesz** [comment]
Tim:  This is going to take a while longer to fix.  There seem to be issues with Hamlib 4.4.  I'm going to merge the issue44 branch into main.

For the time being, I have the following recommendation:  Continue to use Hamlib 4 for rigctld so you can use your FTDX10.  But rebuild rigsync with Hamlib 3.3.  I have tested this configuration (on Ubuntu 20.04) and it works for me.

I don't know what your compilation/linking proficiency is, but I can provide instructions for using Hamlib 3.3 for rebuilding if required.

**Comment by timgrossner** [comment]
I am relatively proficient, but I don't think I have ever compiled
something with a different library than what I have installed. I imagine
it's probably pretty easy, though. If you can provide a guide, I would
welcome it!

I guess it could also be done on another machine that has hamlib 3.3, then
copy the binary over to the hamlib 4.4 machine, no?

**Comment by daveriesz** [comment]
First part:
1.  Get Hamlib 3.3: https://github.com/Hamlib/Hamlib/releases/download/3.3/hamlib-3.3.tar.gz
2.  Configure for a separate install directory (e.g. ```./configure --prefix=/usr/local/hamlib-3.3```)
3.  Build and install: ```make && make install```

Second part:
Edit rigsync's Makefile:
1. ```CINC = -I/usr/local/hamlib-3.3/include```
2. ```LDDIR = -L/usr/local/hamlib-3.3/lib -Wl,-rpath=/usr/local/hamlib-3.3/lib```
and rebuild.

Run ```ldd rigsync``` on the resulting executable and make sure it's picking up the 3.3 version of hamlib.
